# Generated by Django 5.2.8 on 2025-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="uz", max_length=10),
        ),
    ]
